---
- name: "netstart"
  shell: "sh /etc/netstart {{ item.name }}"
  loop: "{{ net.ifaces }}"

- name: "wg_netstart"
  shell: "sh /etc/netstart wg0"

- name: "sysctl_forwarding"
  shell: "/usr/sbin/sysctl net.inet.ip.forwarding=1"

- name: "dhcpd_syntax"
  shell: dhcpd -n

- name: "dhcpd_restart"
  service:
    name: dhcpd
    state: restarted
    enabled: true

- name: "unbound_adblock"
  shell: "{{ 'doas -u _adblock /usr/local/bin/unbound-adblock -O openbsd -w /var/unbound/db/adblock_whitelist' if net.dns.filter.whitelist is defined else 'doas -u _adblock /usr/local/bin/unbound-adblock -O openbsd' }}"

- name: "unbound_restart"
  service:
    name: unbound
    state: restarted
    enabled: true

- name: "dhcpleased_restart"
  service:
    name: dhcpleased
    state: restarted
    enabled: true

- name: "pf_syntax"
  shell: pfctl -f /etc/pf.conf -n

- name: "pf_reload"
  shell: pfctl -f /etc/pf.conf

