---
- name: "obsd : filters : install spam filters"
  community.general.openbsd_pkg:
    name:
      - opensmtpd-filter-senderscore
      - opensmtpd-filter-rspamd
      - rspamd--hyperscan
      - redis
    state: present
  tags:
    - mail
    - listen

- name: "obsd : filters : template configuration"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
  loop:
    - { src: settings.conf.j2, dst: /etc/rspamd/local.d/settings.conf }
#    - { src: dyndns.j2, dst: /etc/mail/dyndns }
  notify:
    - "rspamd_restart"
    - "smtpd_syntax"
    - "smtpd_restart"
  tags:
    - mail
    - listen

- name: "obsd : filters : set up boxes filtering"
  community.general.openbsd_pkg:
    name: dovecot-pigeonhole
    state: present
  when: mail.boxes is defined
  tags:
    - mail
    - listen

