---
- name: "obsd : smtpd : install extras"
  community.general.openbsd_pkg:
    name: opensmtpd-extras
    state: present
  tags:
    - mail

- name: "obsd : smtpd : template the main config"
  template:
    src: smtpd.conf.j2
    dest: /etc/mail/smtpd.conf
    mode: 0600
  notify:
    - "smtpd_syntax"
    - "smtpd_restart"
  tags:
    - mail
    - listen
    - domains
    - whitelist
    - boxes
    - virtuals

- name: "obsd : smtpd : setup domains file"
  template:
    src: domains.j2
    dest: /etc/mail/domains
    mode: 0600
  notify:
    - "smtpd_syntax"
    - "smtpd_restart"
  when: mail.domains is defined
  tags:
    - mail
    - domains

- name: "obsd : smtpd : set up whitelist"
  template:
    src: "{{ item }}.j2"
    dest: "/etc/mail/{{ item }}"
    mode: 0600
  loop:
    - whitelist
  notify:
    - "smtpd_syntax"
    - "smtpd_restart"
  tags:
    - mail
    - whitelist

- name: "obsd : smtpd : set up tables"
  template:
    src: "{{ item }}.j2"
    dest: "/etc/mail/{{ item }}"
    mode: 0600
  loop:
    - passwd
    - virtuals
  notify:
    - "smtpd_syntax"
    - "smtpd_restart"
  when: mail.users is defined or mail.boxes is defined
  tags:
    - mail
    - boxes
    - users
    - virtuals

- name: "obsd : smtpd : set up filters"
  include_tasks: openbsd_filters.yaml
  when: mail.listen | selectattr('filter', 'eq', 'spam') | length > 0
  tags:
    - mail
    - listen

- name: "obsd : smtpd : set up dkim"
  include_tasks: openbsd_dkim.yaml
  when: mail.listen | selectattr('dkim', 'true') | length > 0
  tags:
    - mail
    - listen
    - domains
    - setup

- name: "obsd : smtpd : set up boxes"
  include_tasks: openbsd_boxes.yaml
  when: mail.boxes is defined
  tags:
    - mail
    - boxes

