---
- ansible.builtin.debug: # noqa unnamed-task
    msg: creating {{ instancename }} from {{ template }} on {{ runon }}
  when: action == 'create'

- ansible.builtin.debug: # noqa unnamed-task
    msg: destroying {{ instancename }} on {{ runon }}
  when: action == 'destroy'

- name: check host platform
  ansible.builtin.setup:
  register: arch
  delegate_to: "{{ runon }}"
  delegate_facts: true

- name: "openbsd : vmd"
  include_tasks: vmd.yaml
  when: hostvars[runon]['ansible_distribution']|lower == 'openbsd'
