---
#- name: set connection options
#  ansible.builtin.set_fact:
#    ansible_become_method: doas
#    ansible_become: true
#  delegate_to: "{{ runon }}"
#  delegate_facts: true

- name: sanity checks
  include_tasks: vmd_prereqs.yaml

- name: create VM
  include_tasks: vmd_create.yaml
  when: action == 'create'

- name: destroy VM
  include_tasks: vmd_destroy.yaml
  when: action == 'destroy'
