---
# if the file doesn't exist don't create it
# this is to pass the no-change-on-no-config check
- name: "obsd : check if crontab exists"
  ansible.builtin.stat:
    path: /etc/crontab
  register: crontab

- name: "obsd : setup crontab"
  ansible.builtin.template:
    src: crontab.j2
    dest: /etc/crontab
    mode: 0600
  when: ansible_facts['os_family']|lower == 'openbsd' and crontab.stat.exists
