---
- hosts: all
  become_method: doas

  tasks:
    - name: "find : obsd : find ethernets"
      shell: "echo; for iface in $(ifconfig | grep -E '^[a-z]+[0-9]:' | cut -d ':' -f1 | grep -vE 'pflog[0-9]|enc[0-9]|lo[0-9]|wg[0-9]' | tr '\n' ' '); do mac=$(ifconfig $iface | grep lladdr | cut -d ' ' -f2); echo $iface $mac; done"
      register: ethernets

    - name: "find : obsd : echo facts"
      debug:
        msg: "Available ethernets on {{ ansible_fqdn }}: {{ ethernets.stdout }}"

