---
- name: "virt : OpenBSD vmd"
  include_tasks: openbsd_vmd.yaml
  when: virt is defined and ansible_facts['os_family']|lower == 'openbsd'
  tags:
    - virt

#- name: Debian specifics
#  include_tasks: debian.yaml
#  when: ansible_facts['os_family']|lower == 'debian'
#
#- name: Cross-platform base
#  include_tasks: httpd.yaml
#
