---
- name: "obsd : imgs : obsd : grab version"
  shell: ftp -o - http://ftp.openbsd.org/pub/OpenBSD/ | grep '"[0-9]\.[0-9]/"' | sed -e 's/\/<\/a>.*//' -e 's/.*>//' | sort | tail -n1
  register: obsd_latest
  changed_when: false
  tags:
    - virt

- name: "obsd : imgs : obsd : download time notif"
  debug:
    msg: "Downloading the latest OpenBSD ISO. This will take a while."
  tags:
    - virt

- name: "obsd : imgs : obsd : grab latest iso"
  get_url:
    url: "https://cdn.openbsd.org/pub/OpenBSD/{{ obsd_latest.stdout }}/amd64/install{{ obsd_latest.stdout | replace('.', '') }}.iso"
    dest: /home/isos/openbsd.iso
  tags:
    - virt

