---
- name: "obsd : imgs : alp : determine major version"
  shell: ftp -o - https://dl-cdn.alpinelinux.org/alpine/ | grep '"v[0-9]\.[0-9]./"' | sed -e 's/\/<\/a>.*//' -e 's/.*>//' | sort | tail -n1
  register: alp_latest_major
  tags:
    - virt

- name: "obsd : imgs : alp : determine minor version"
  shell: "ftp -o - https://dl-cdn.alpinelinux.org/alpine/{{ alp_latest_major.stdout }}/releases/x86_64 | tr '=' '\n' | grep alpine-standard-{{ alp_latest_major.stdout | replace('v', '') }} | cut -d '>' -f1 | grep -vE 'rc|sha|asc' | sort | tail -n1"
  register: alp_latest
  tags:
    - virt

- name: "obsd : imgs : alp : download time notif"
  debug:
    msg: "Downloading the latest Alpine ISO. This will take a while."
  tags:
    - virt

- name: "obsd : imgs : alp : fetch latest iso"
  get_url:
    url: "https://dl-cdn.alpinelinux.org/alpine/{{ alp_latest_major.stdout }}/releases/x86_64/{{ alp_latest.stdout | replace('\"', '') }}"
    dest: "/home/isos/alpine_staging_{{ randomid }}.iso"
  tags:
    - virt

- name: "obsd : imgs : alp : stage files"
  shell: "xorriso -osirrox on -indev /home/isos/alpine_staging_{{ randomid }}.iso -extract / /home/isos/alpine_staging_files_{{ randomid }}/"
  tags:
    - virt

- name: "obsd : imgs : alp : conf serial output"
  shell: "{{ item }}"
  loop:
    - "echo -n 'TIMEOUT 20\nPROMPT 1\nDEFAULT lts\n\nLABEL lts\nMENU LABEL Linux lts\nKERNEL /boot/vmlinuz-lts\nINITRD /boot/initramfs-lts\nFDTDIR /boot/dtbs-lts\nAPPEND cga=off console=ttyS0,115200n8 modules=loop,squashfs,sd-mod,usb-storage vga=off console=tty0,115200n8\n' > /home/isos/alpine_staging_files_{{ randomid }}/boot/syslinux/syslinux.cfg"
    - "sed -i'' 's/quiet/console=ttyS0,115200n8/g' /home/isos/alpine_staging_files_{{ randomid }}/boot/grub/grub.cfg"
  tags:
    - virt

- name: "obsd : imgs : alp : repackage iso"
  shell: "xorriso -as mkisofs -o /home/isos/alpine.iso -isohybrid-mbr /home/isos/alpine_staging_files_{{ randomid }}/boot/syslinux/isohdpfx.bin -c boot/syslinux/boot.cat -b boot/syslinux/isolinux.bin -no-emul-boot -boot-load-size 4 -boot-info-table /home/isos/alpine_staging_files_{{ randomid }}"
  tags:
    - virt

- name: "obsd : imgs : alp : clean up"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/home/isos/alpine_staging_files_{{ randomid }}"
    - "/home/isos/alpine_staging_{{ randomid }}.iso"
  tags:
    - virt

