# this playbook file exists to be called by fsa.sh
---
- hosts: "{{ target | default('all') }}"
  gather_facts: false
  tasks:
    - name: check OS
      ansible.builtin.raw: uname
      register: uname
      changed_when: false

    - name: set connection facts
      ansible.builtin.set_fact:
        ansible_host: "{{ fsa.addr | default(inventory_hostname) }}"
        ansible_port: "{{ fsa.port | default('22') }}"
        ansible_become: "{{ true if fsa.user | default(lookup('pipe', 'whoami')) != 'root' else false }}"
        ansible_become_method: "{{ 'doas' if 'OpenBSD' in uname.stdout else 'sudo' }}"
      changed_when: false

    - name: bootstrap
      ansible.builtin.raw: which python3 || pkg_add python3 || apk add python3 || apt install python3
      when: fsa.bootstrap|default(true)
      changed_when: false

    # also serves as a failcheck
    - name: gather facts
      ansible.builtin.setup:
