---
- name: "acme_syntax"
  shell: acme-client -n

  # this includes the fullchain copy for relayd, just in case
- name: "acme_request"
  shell: for i in $(cat /etc/acme-client.conf | grep ^domain | cut -d ' ' -f2); do /usr/sbin/acme-client -v $i; cp /etc/ssl/$i.fullchain.pem /etc/ssl/$i.crt; done

- name: "httpd_syntax"
  shell: httpd -n

- name: "httpd_restart"
  service:
    name: httpd
    state: restarted
    enabled: true

- name: "php_syntax"
  shell: "php-fpm-{{ web.httpd.php.version.split('.')[0:2] | join('.') }} -t"

- name: "php_restart"
  service:
    name: "php{{ web.httpd.php.version.split('.')[0:2] | join('') }}_fpm"
    state: restarted
    enabled: true

- name: "relayd_syntax"
  shell: relayd -n

- name: "relayd_restart"
  service:
    name: relayd
    state: restarted
    enabled: true

