---
# mail also requires ssl
- name: "obsd : httpd/relayd"
  include_tasks: openbsd_web.yaml
  when: (web is defined or mail is defined) and ansible_facts['os_family']|lower == 'openbsd'
  tags:
    - web
    - mail
    - httpd
    - sites
    - auth
    - relay

#- name: Debian specifics
#  include_tasks: debian.yaml
#  when: ansible_facts['os_family']|lower == 'debian'
#
#- name: Cross-platform base
#  include_tasks: httpd.yaml
#
