---
- name: "obsd : relay : template the config"
  template:
    src: relayd.conf.j2
    dest: /etc/relayd.conf
    mode: 0600
  notify:
    - "relayd_syntax"
    - "relayd_restart"
  tags:
    - web
    - relay
    - sites

