---
- name: "obsd : tls : configure acme-client"
  template:
    src: acme-client.conf.j2
    dest: /etc/acme-client.conf
    mode: 0600
  notify:
    - "acme_syntax"
    - "acme_request"
  tags:
    - web
    - mail
    - sites
    - relay

