---
- name: fail if install is set
  ansible.builtin.fail:
    msg: Cannot have `install` and `template` set simultaneously
  when: item.template is defined and item.install is defined

# to make sure the disk file isn't being modified as we copy it
- name: make sure VM exists # noqa risky-shell-pipe
  ansible.builtin.shell: "[ -f /home/vms/{{ item.name }}.img ]"
  loop: "{{ virt.vms }}"
  when: item.template is defined

# sleep a bit at the end for safety
- name: stop VM if running # noqa risky-shell-pipe
  ansible.builtin.shell: if vmctl show | grep {{ item.name }} | grep -q running; then vmctl stop {{ item.name }}; while true;
    do if vmctl show | grep {{ item.name }} | grep -q stopped; then break; sleep 5; else sleep 2; fi; done; fi
  loop: "{{ virt.vms }}"
  when: item.template is defined

- name: copy template
  ansible.builtin.copy:
    src: /home/vms/{{ item.name }}.img
    dest: /home/isos/fsa-template-{{ item.template }}.img
    remote_src: true
    mode: 0600
  loop: "{{ virt.vms }}"
  when: item.template is defined
