---
- name: "obsd : Firmware check"
  shell: fw_update
  register: fw_update
  changed_when: fw_update.rc != 0
  tags:
    - update

- name: "obsd : Base updates"
  community.general.syspatch:
  register: syspatch
  notify:
    - "openbsd_reboot"
  tags:
    - update

- name: "obsd : Package updates"
  community.general.openbsd_pkg:
    name: '*'
    state: latest
  tags:
    - update
