---
- name: "obsd : vpn : server : check routing enabled"
  ansible.builtin.fail:
    msg: VPN server requires net.routing = true
  when: net.routing is undefined or not net.routing

- name: "obsd : vpn : server : connect to clients"
  ansible.builtin.include_role:
    name: fsa_connect
  vars:
    target: "{{ item.name }}"
  loop: "{{ net.vpn.peers }}"

- name: "obsd : vpn : server : grab pubkeys"
  ansible.builtin.command: cat /etc/wireguard/public.key
  delegate_to: "{{ item.name }}"
  loop: "{{ net.vpn.peers }}"
  register: peer_pubkeys
  no_log: true
  changed_when: false
  when: net.vpn.peers is defined
  notify:
    - wg_netstart

- name: "obsd : vpn : server : grab privkey"
  ansible.builtin.command: cat /etc/wireguard/secret.key
  register: host_privkey
  no_log: true
  changed_when: false
  notify:
    - wg_netstart

- name: "obsd : vpn : server : grab psk"
  ansible.builtin.command: cat /etc/wireguard/preshared.key
  register: own_psk
  no_log: true
  changed_when: false
  when: net.vpn.psk | default(false)
  notify:
    - wg_netstart
