---
- name: "obsd : vpn : client : connect to server"
  ansible.builtin.include_role:
    name: fsa_connect
  vars:
    target: "{{ net.vpn.peer.name }}"

- name: "obsd : vpn : client : grab pubkey"
  ansible.builtin.command: cat /etc/wireguard/public.key
  delegate_to: "{{ net.vpn.peer.name }}"
  register: peer_pubkey
  no_log: true
  changed_when: false
  notify:
    - wg_netstart

- name: "obsd : vpn : client : grab privkey"
  ansible.builtin.command: cat /etc/wireguard/secret.key
  register: host_privkey
  no_log: true
  changed_when: false
  notify:
    - wg_netstart

- name: "obsd : vpn : client : grab psk"
  ansible.builtin.command: cat /etc/wireguard/preshared.key
  delegate_to: "{{ net.vpn.peer.name }}"
  register: peer_psk
  no_log: true
  changed_when: false
  when: net.vpn.psk | default(false)
  notify:
    - wg_netstart
