---
- name: "apps : dav : prerequisites"
  community.general.openbsd_pkg:
    name: unzip--
    state: present
  tags:
    - apps
    - dav

- name: "apps : dav : determine install path"
  set_fact:
    davsite: "{{ item }}"
  when: apps.dav.site in item.name
  loop: "{{ web.sites }}"
  tags:
    - apps
    - dav

- name: "apps : dav : web.site check"
  fail:
    msg: "Select a valid web.site for your app"
  when: davsite is undefined
  tags:
    - apps
    - dav

- name: "apps : dav : check if already installed"
  stat:
    path: "/var/www{{ davsite.root }}/Specific"
  register: davinstalled
  tags:
    - apps
    - dav

- name: "apps : dav : unpack v{{ baikal_version }}"
  unarchive:
    src: "https://github.com/sabre-io/Baikal/releases/download/{{ baikal_version }}/baikal-{{ baikal_version }}.zip"
    dest: /tmp/
    remote_src: true
  tags:
    - apps
    - dav
  when: not davinstalled.stat.exists

# yep. moving files with ansible sucks
- name: "apps : dav : take live"
  shell: "cp -r /tmp/baikal/* /var/www{{ davsite.root }}/"
  tags:
    - apps
    - dav
  when: not davinstalled.stat.exists

- name: "apps : dav : set permissions"
  file:
    path: "/var/www/webdav/{{ item }}"
    owner: www
    recurse: true
  loop:
    - Specific
    - config
  tags:
    - apps
    - dav

- name: "apps : dav : set admin users"
  shell: "echo {{ item.user }}:{{ item.pass }} | htpasswd -I /var/www{{ davsite.root }}/.auth && chown :www /var/www{{ davsite.root }}/.auth && chmod 0640 /var/www{{ davsite.root }}/.auth"
  changed_when: false
  loop: "{{ apps.dav.admin }}"
  tags:
    - apps
    - dav

