---
- name: "vmd_syntax"
  shell: vmd -n

- name: "vmd_running"
  service:
    name: vmd
    state: started
    enabled: true

- name: "vmd_reload"
  service:
    name: vmd
    state: reloaded
    enabled: true

- name: "vmd_netstart"
  shell: "sh /etc/netstart bridge0"

