---
- name: "net : OpenBSD networking"
  include_tasks: openbsd_net.yaml
  when: net is defined and ansible_facts['os_family']|lower == 'openbsd'
  tags:
    - net
    - ifaces
    - dhcp
    - dns
    - vpn
    - fw

#- name: Debian specifics
#  include_tasks: debian.yaml
#  when: ansible_facts['os_family']|lower == 'debian'
#
#- name: Cross-platform base
#  include_tasks: httpd.yaml
#
