---
- name: "obsd : base : configure interfaces"
  template:
    src: hostname.j2
    dest: "/etc/hostname.{{ item.name }}"
    mode: 0600
  loop: "{{ net.ifaces }}"
  notify:
    - "netstart"
  when: net.ifaces is defined
  tags:
    - net
    - ifaces

- name: "obsd : base : set up ip forwarding"
  lineinfile:
    path: /etc/sysctl.conf
    create: true
    mode: 0600
    line: net.inet.ip.forwarding=1
  when: net.routing is defined and net.routing
  notify:
    - "sysctl_forwarding"
  tags:
    - net
    - ifaces
    - vpn

- name: "obsd : base : set up routes"
  shell: "route add -inet {{ item }}"
  when: net.routes is defined
  loop: "{{ net.routes }}"
  register: route
  changed_when: route.rc == 0
  failed_when: false
  tags:
    - net
    - ifaces

- name: "obsd : base : run dhcpd"
  include_tasks: openbsd_dhcpd.yaml
  when: net.ifaces | selectattr('dhcp', 'defined') | length > 0
  tags:
    - net
    - dhcp

- name: "obsd : base : run unbound"
  include_tasks: openbsd_unbound.yaml
  when: net.dns is defined
  tags:
    - net
    - dns

- name: "obsd : base : run wireguard"
  include_tasks: openbsd_wireguard.yaml
  tags:
    - net
    - vpn

- name: "obsd : base : run badhost"
  include_tasks: openbsd_badhost.yaml
  when: net.public | default(false)
  tags:
    - net
    - fw

- name: "obsd : base : conf firewall"
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf
    mode: 0600
  notify:
    - "pf_syntax"
    - "pf_reload"
  tags:
    - net
    - fw

