---
- name: "obsd : vpn : server : check routing enabled"
  fail:
    msg: "VPN server requires net.routing = true"
  when: net.routing is undefined or not net.routing
  tags:
    - net
    - vpn

- name: "obsd : vpn : server : grab pubkeys"
  shell: "cat /etc/wireguard/public.key"
  delegate_to: "{{ item.name }}"
  loop: "{{ net.vpn.peers }}"
  register: "peer_pubkeys"
  no_log: true
  changed_when: false
  when: net.vpn.peers is defined
  notify:
    - "wg_netstart"
  tags:
    - net
    - vpn

- name: "obsd : vpn : server : grab privkey"
  shell: "cat /etc/wireguard/secret.key"
  register: "host_privkey"
  no_log: true
  changed_when: false
  notify:
    - "wg_netstart"
  tags:
    - net
    - vpn

- name: "obsd : vpn : server : grab psk"
  shell: "cat /etc/wireguard/preshared.key"
  register: "own_psk"
  no_log: true
  changed_when: false
  when: net.vpn.psk | default(false)
  notify:
    - "wg_netstart"
  tags:
    - net
    - vpn

- name: "obsd : vpn : server : set up iface"
  template:
    src: hostname.wgX.j2
    dest: /etc/hostname.wg0
    mode: 0600
  notify:
    - "wg_netstart"
  tags:
    - net
    - vpn

