---
# point resolv.conf to localhost, tell dhcpleased to ignore server-provided dns
- name: "obsd : dns : template the config"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    mode: 0644
  loop:
    - { src: "unbound.conf.j2", dst: "/var/unbound/etc/unbound.conf" }
    - { src: "resolv.conf.j2", dst: "/etc/resolv.conf" }
    - { src: "dhcpleased.conf.j2", dst: "/etc/dhcpleased.conf" }
  notify:
    - "unbound_restart"
    - "dhcpleased_restart"
  tags:
    - net
    - dns

- name: "obsd : dns : set up logfile"
  file:
    path: "/var/log/unbound"
    state: touch
    mode: 0640
  changed_when: false
  tags:
    - net
    - dns

# convenience
- name: "obsd : dns : symlink it to /etc"
  file:
    src: /var/unbound/etc/unbound.conf
    dest: /etc/unbound.conf
    state: link
  tags:
    - net
    - dns

- name: "obsd : dns : check if DNSSEC KSK exists"
  stat:
    path: /var/unbound/db/root.key
  register: ksk
  tags:
    - net
    - dns

- name: "obsd : dns : not exists. generate..."
  shell: /usr/sbin/unbound-anchor -a /var/unbound/db/root.key
  when: not ksk.stat.exists
  failed_when: false
  notify:
    - "unbound_restart"
  tags:
    - net
    - dns

- name: "obsd : dns : get root hints"
  get_url:
    url: https://www.internic.net/domain/named.root
    dest: /var/unbound/etc/root.hints
  notify:
    - "unbound_restart"
  tags:
    - net
    - dns

- name: "obsd : dns : set up filtering"
  include_tasks: openbsd_adblock.yaml
  when: net.dns.filter | default(true)
  tags:
    - net
    - dns

