---
- name: "obsd : set hostname"
  ansible.builtin.lineinfile:
    path: /etc/myname
    regexp: ^
    line: "{{ base.name }}"
  when: base.name is defined

- name: "obsd : also for current session"
  ansible.builtin.command: hostname {{ base.name }}
  when: base.name is defined
  changed_when: false

- name: "obsd : enable/disable sound"
  ansible.builtin.service:
    name: sndiod
    enabled: "{{ base.sound | default(false) }}"
    state: "{{ 'started' if base.sound | default(false) else 'stopped' }}"

# might not come back up by itself otherwise
- name: "obsd : setup auto-fsck" # noqa no-tabs
  ansible.builtin.lineinfile:
    path: /etc/rc
    line: "\tfsck -p -y \"$@\""
    regexp: "\tfsck -p"

- name: "obsd : template motd" # noqa risky-file-permissions
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
