---
- name: mariadb_restart
  ansible.builtin.service:
    name: mariadb
    state: restarted
    enabled: true

- name: mysqld_restart
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: true
