---
- name: "sshguard : install the package"
  community.general.openbsd_pkg:
    name: sshguard
    state: present
  tags:
    - sshd

- name: "sshguard : template the config"
  template:
    src: sshguard.conf.j2
    dest: /etc/sshguard.conf
    mode: 0600
  notify:
    - "sshguard_restart"
  tags:
    - sshd

