---
- name: "obsd : set hostname"
  lineinfile:
    path: /etc/myname
    regexp: '^'
    line: "{{ base.name }}"
  tags:
    - base

- name: "obsd : install base packages"
  community.general.openbsd_pkg:
    name:
      - htop
      - vim--no_x11
    state: present
  tags:
    - base

- name: "obsd : setup crontab"
  template:
    src: crontab.j2
    dest: /etc/crontab
    mode: 0600
  tags:
    - base
    - net
    - routes
    - vpn
    - fw
    - web
    - mail
    - cron

- name: "obsd : disable sound"
  service:
    name: sndiod
    enabled: false
    state: stopped
  when: base.sound | default(false)
  tags:
    - base

- name: "obsd : setup doas"
  template:
    src: doas.conf.j2
    dest: /etc/doas.conf
    mode: 0600
  tags:
    - base
    - net
    - dns

- name: "obsd : setup auto-fsck"
  lineinfile:
    path: /etc/rc
    line: '	fsck -p -y "$@"'
    regexp: '	fsck -p'
  tags:
    - base

- name: "obsd : setup syslog.conf"
  template:
    src: syslog.conf.j2
    dest: /etc/syslog.conf
    mode: 0644
  notify:
    "syslogd_restart"
  tags:
    - base
    - dhcp
    - dns
    - relay

# must be setup manually
- name: "obsd : setup logfiles"
  file:
    path: "/var/log/{{ item.filename }}"
    state: touch
  when: item.condition
  loop:
    - {filename: "unbound.log", condition: "net.dns is defined" }
    - {filename: "dhcpd.log", condition: "net.ifaces | selectattr('dhcp', 'defined') | length > 0" }
    - {filename: "relayd.log", condition: "web.relay is defined" }
  changed_when: false
  notify:
    "syslogd_restart"
  tags:
    - base
    - dhcp
    - dns
    - relay

- name: "obsd : set up admin user"
  user:
    name: "{{ base.user }}"
    password: "{{ '*************' if base.userpw is not defined else base.userpw }}"
  tags:
    - base

#- name: "obsd : set aliases"
#  blockinfile:
#    path: /root/.profile
#    block: |
#      alias poweroff="shutdown -p now"
#      alias testalias=somestring
#    marker: "# useful aliases {mark}"
#  tags:
#    - base

