---
- name: run sshd
  include_tasks: generic_sshd.yaml
  when: base.sshd is defined and base.sshd.enabled | default(true)

- name: run sshguard
  include_tasks: generic_sshguard.yaml
  when: base.sshd.guard | default(false)
