---
- name: "sshguard : install the package"
  community.general.openbsd_pkg:
    name: sshguard
    state: present

- name: "sshguard : template the config"
  ansible.builtin.template:
    src: sshguard.conf.j2
    dest: /etc/sshguard.conf
    mode: 0600
  notify:
    - sshguard_restart
